Buttons/Models/Movies.cs
using System;

namespace Prac4.Models
{
    public class Movies
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public string Author { get; set; }
        public string Relise_Date { get; set; }

        public Movies(string name, string genre,string author,string reliseDate,int id = 0)
        {
            Id = id;
            Name = name;
            Genre = genre;
            Author = author;
            Relise_Date = reliseDate;
        }

        public Movies(){}
    }
}

Buttons/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Prac4.Models;

namespace Prac4.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class MoviesController:Controller
    {
        private readonly DbMovieContext _context;
        public MoviesController(DbMovieContext dbMovieContext)
        {
            _context = dbMovieContext;
        }
        [HttpGet]
        public async Task<IEnumerable<Movies>> Get()
        {
            return await _context.GetAllAsync();
        }
        
        [HttpGet("get/{id}")]
        public async Task<Movies> Get(string id)
        {
            var tmp = await _context.GetByIdAsync(int.Parse(id));
            return tmp.FirstOrDefault();
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromForm] string id, [FromForm] string name,[FromForm] string janr,[FromForm] string author,[FromForm] string reliseDate)
        {
            await _context.InsertAsync(new Movies()
            {
                Author = author,
                Genre = janr,
                Name = name,
                Relise_Date = reliseDate,
            });
            return Ok();
        }
        [HttpPut]
        public async Task<IActionResult> Put([FromForm] string currentId,[FromForm] string changedId, [FromForm] string name,[FromForm] string janr,[FromForm] string author,[FromForm] string reliseDate)
        {
            await _context.UpdateAsync(int.Parse(currentId), new Movies()
            {
                Author = author,
                Genre = janr,
                Name = name,
                Relise_Date = reliseDate,
            });
            

            return Ok();
        }

        [HttpDelete]
        public async Task<IActionResult> Delete([FromForm] string id)
        {
            await _context.DeleteAsync(int.Parse(id));
            return Ok();
        }
    }
}

Buttons/Pages/Chat.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Prac4.Pages
{
    public class Chat : PageModel
    {


        public void OnPostEnter(string name)
        {
            var session = HttpContext.Session;
            session.SetString("name",name);
        }
        public void OnPostLogout()
        {
            var session = HttpContext.Session;
            session.Remove("name");
        }
    }
}

Buttons/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Prac4.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Buttons/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Prac4.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Buttons/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Prac4.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Buttons/Pages/Chat.cshtml
@page
@model Prac4.Pages.Chat
@{
    ViewData["Title"] = "Chat";
}
@inject ChatManager ChatManager
<div class="row top-space">
    @{
        var session = HttpContext.Session;
        if (session.Keys.Contains("name"))
        {
            <div class="col-md-12">
                <ul id="messages">
                    @foreach (var v in ChatManager.Messages)
                    {
                        <li>@v.UserId : @v.Message</li>
                    }
                </ul>
                <input class="form-control" id="message-content"/>
            </div>
        }
        else
        {
            <h1>Для того чтобы воспользоваться чатом войдите в систему</h1>
        }
    }
</div>

@section Scripts{
    <script data-main="scripts/main" src="js/WebSocketManager.js"></script>
}

Buttons/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<table class="table table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Author</th>
        <th scope="col">Relise</th>
    </tr>
    </thead>
    <tbody id="tableBody">
    
    </tbody>
</table>
<div id="formsContent">
    <div id="divInfo" class="divForm">
        <button type="button" id="btnInfo" class="btn btn-dark">Info</button>
        <form id="formInfo" style="display: none">
            <div class="form-group">
                <label for="formInputInfo">Enter Id</label>
                <input type="text" class="form-control" id="formInputInfo" placeholder="Id">
            </div>
            <div class="form-group">
                <labe id="lblInfo"></labe>
            </div>
            <input class ="btn btn-dark" type="submit" name="Find" value="Find" id="sbmtInfo">
        </form>
        
    </div>
    <div id="divAdd" class="divForm">
        <button type="button" id="btnAdd" class="btn btn-dark">Add</button>
        <form id="formAdd" style="display: none" method="POST" onsubmit="return addRecord();">
            <div class="form-group">
                <label for="formInputAdd">Enter data</label>
                <input type="text" class="form-control" id="formInputId" name="id" placeholder="Id">
                <input type="text" class="form-control" id="formInputName" name="name"  placeholder="Name">
                <input type="text" class="form-control" id="formInputJanr" name="janr" placeholder="Janr">
                <input type="text" class="form-control" id="formInputAuthor" name="author" placeholder="Author">
                <input type="text" class="form-control" id="formInputReliseDate" name="reliseDate" placeholder="Relise date">
            </div>
            <div class="form-group">
                <labe id="lblAdd"></labe>
            </div>
            <input class ="btn btn-dark" type="submit" name="Add" value="Add" id="sbmtAdd">
        </form>
    </div>
    <div id="divUpdate" class="divForm">
        <button type="button" id="btnUpdate" class="btn btn-dark">Update</button>
        <form id="formUpdate" style="display: none" method="POST" onsubmit="return updateRecord();">
                    <div class="form-group">
                        <label for="formInputCurrentId">Enter current id</label>
                        <input type="text" class="form-control" id="formInputCurrentId" name="currentId" placeholder="Current id">
                        <label for="formInputUpdateId">Enter new data</label>
                        <input type="text" class="form-control" id="formInputUpdateId" name="changedId" placeholder="New id">
                        <input type="text" class="form-control" id="formInputUpdateName" name="name"  placeholder="New name">
                        <input type="text" class="form-control" id="formInputUpdateJanr" name="janr" placeholder="New janr">
                        <input type="text" class="form-control" id="formInputUpdateAuthor" name="author" placeholder="New author">
                        <input type="text" class="form-control" id="formInputUpdateReliseDate" name="reliseDate" placeholder="New relise date">
                    </div>
                    <div class="form-group">
                        <labe id="lblUpdate"></labe>
                    </div>
                    <input class ="btn btn-dark" type="submit" name="Update" value="Update" id="sbmtUpdate">
                </form>
    </div>
    <div id="divDelete" class="divForm">
        <button type="button" id="btnDelete" class="btn btn-dark">Delete</button>
        <form id="formDelete" style="display: none" onsubmit="return deleteRecord();">
                    <div class="form-group">
                        <label for="formInputDelete">Enter Id</label>
                        <input type="text" class="form-control" id="formInputDelete" placeholder="Id">
                    </div>
                    <div class="form-group">
                        <labe id="lblDelete"></labe>
                    </div>
                    <input class ="btn btn-dark" type="submit" name="Delete" value="Delete" id="sbmtDelete">
                </form>
    </div>
</div>

Buttons/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">Prac4</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Chat">Chat</a>
                    </li>
                </ul>
            </div>
            @{
                var session = Context.Session;
                if (!session.Keys.Contains("name"))
                {
                    <div class="dropdown" id="dropdownEnter">
                        <button class="btn btn-enter dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Войти
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <form class="dropdown-item" method="POST" asp-page-handler="Enter">
                                <div class="form-group">
                                    <label for="nickName">Имя</label>
                                    <input type="text" class="form-control" id="nickName" aria-describedby="nickNameHelp" name="name">
                                    <small id="nickNameHelp" class="form-text text-muted">Введите Ваше имя.</small>
                                </div>
                                <button type="submit" class="btn btn-enter">Войти</button>
                            </form>
                        </div>
                    </div>
                }
                else
                {
                    <div class="dropdown" id="dropdownLogout">
                        <button class="btn btn-enter dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @session.GetString("name")
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <form class="dropdown-item" method="POST" asp-page-handler="Logout">
                                <button type="submit" class="btn btn-enter">Выйти</button>
                            </form>
                        </div>
                    </div>
                }
            }
            @*<div class="dropdown" id="dropdownEnter">
                <button class="btn btn-enter dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Войти
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <form class="dropdown-item" method="POST" asp-page-handler="Enter">
                        <div class="form-group">
                            <label for="nickName">Имя</label>
                            <input type="text" class="form-control" id="nickName" aria-describedby="nickNameHelp" name="name">
                            <small id="nickNameHelp" class="form-text text-muted">Введите Ваше имя.</small>
                        </div>
                        <button type="submit" class="btn btn-enter">Войти</button>
                    </form>
                </div>
            </div>
            
            <div class="dropdown" id="dropdownLogout">
                <button class="btn btn-enter dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    НИК
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <form class="dropdown-item" method="POST" asp-page-handler="Logout">
                        <button type="submit" class="btn btn-enter">Выйти</button>
                    </form>
                </div>
            </div>*@
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Prac4 - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>